var dir_981ed64f854a2c791f78f1fb5772f37f =
[
    [ "AreaSummationStateInfo.m", "_area_summation_state_info_8m.html", null ],
    [ "Back_PropagationStateInfo.m", "_back___propagation_state_info_8m.html", null ],
    [ "ColourGratingStateInfo.m", "_colour_grating_state_info_8m.html", null ],
    [ "DMTSFunctions.m", "_d_m_t_s_functions_8m.html", "_d_m_t_s_functions_8m" ],
    [ "DMTSStateInfo.m", "_d_m_t_s_state_info_8m.html", null ],
    [ "DotColourStateInfo.m", "_dot_colour_state_info_8m.html", null ],
    [ "DotDirectionStateInfo.m", "_dot_direction_state_info_8m.html", null ],
    [ "FastRFMapperStateInfo.m", "_fast_r_f_mapper_state_info_8m.html", null ],
    [ "FigureGroundStateInfo.m", "_figure_ground_state_info_8m.html", null ],
    [ "FixationOnly.m", "_fixation_only_8m.html", null ],
    [ "FixationTrainingAnimatedStateInfo.m", "_fixation_training_animated_state_info_8m.html", null ],
    [ "FixationTrainingDistractorStateInfo.m", "_fixation_training_distractor_state_info_8m.html", null ],
    [ "FixationTrainingStateInfo.m", "_fixation_training_state_info_8m.html", null ],
    [ "fNIRS.m", "f_n_i_r_s_8m.html", null ],
    [ "Isoluminant_Colours_StateInfo.m", "_isoluminant___colours___state_info_8m.html", null ],
    [ "myUserFunctions.m", "my_user_functions_8m.html", "my_user_functions_8m" ],
    [ "OrientationTuningStateInfo.m", "_orientation_tuning_state_info_8m.html", null ],
    [ "PupillaryReflex.m", "_pupillary_reflex_8m.html", null ],
    [ "RevCorStateInfo.m", "_rev_cor_state_info_8m.html", null ],
    [ "RFLocaliserStateInfo.m", "_r_f_localiser_state_info_8m.html", null ],
    [ "Saccade_AntiSaccade.m", "_saccade___anti_saccade_8m.html", null ],
    [ "Saccade_AntiSaccade_touch.m", "_saccade___anti_saccade__touch_8m.html", null ],
    [ "Saccade_AntiSaccade_TRAIN_1.m", "_saccade___anti_saccade___t_r_a_i_n__1_8m.html", null ],
    [ "SaccadePhospheneStateInfo.m", "_saccade_phosphene_state_info_8m.html", null ],
    [ "Saccadic_Countermanding.m", "_saccadic___countermanding_8m.html", null ],
    [ "Saccadic_DoubleStep.m", "_saccadic___double_step_8m.html", null ],
    [ "Saccadic_DoubleStep_touch.m", "_saccadic___double_step__touch_8m.html", null ],
    [ "Saccadic_DoubleStep_TRAIN_1.m", "_saccadic___double_step___t_r_a_i_n__1_8m.html", null ],
    [ "SFTFStateInfo.m", "_s_f_t_f_state_info_8m.html", null ],
    [ "Two_Images.m", "_two___images_8m.html", null ],
    [ "TwoFigureGroundStateInfo.m", "_two_figure_ground_state_info_8m.html", null ],
    [ "VEPTest.m", "_v_e_p_test_8m.html", null ]
];