var searchData=
[
  ['calibrateluminance_2em_0',['calibrateLuminance.m',['../calibrate_luminance_8m.html',1,'']]],
  ['calibrateluminancenew_2em_1',['calibrateLuminanceNew.m',['../calibrate_luminance_new_8m.html',1,'']]],
  ['calibratesize_2em_2',['calibrateSize.m',['../calibrate_size_8m.html',1,'']]],
  ['ccal_2em_3',['ccal.m',['../ccal_8m.html',1,'']]],
  ['changelog_2emd_4',['CHANGELOG.md',['../_c_h_a_n_g_e_l_o_g_8md.html',1,'']]],
  ['checkerboardstimulus_2em_5',['checkerboardStimulus.m',['../checkerboard_stimulus_8m.html',1,'']]],
  ['colourgratingstateinfo_2em_6',['ColourGratingStateInfo.m',['../_colour_grating_state_info_8m.html',1,'']]],
  ['colourgratingstimulus_2em_7',['colourGratingStimulus.m',['../colour_grating_stimulus_8m.html',1,'']]],
  ['colourmanager_2em_8',['colourManager.m',['../colour_manager_8m.html',1,'']]],
  ['colourtest_2em_9',['colourTest.m',['../colour_test_8m.html',1,'']]],
  ['createproceduralcheckerboard_2em_10',['CreateProceduralCheckerboard.m',['../_create_procedural_checkerboard_8m.html',1,'']]],
  ['createproceduralpolarboard_2em_11',['CreateProceduralPolarBoard.m',['../_create_procedural_polar_board_8m.html',1,'']]],
  ['createproceduralpolargrating_2em_12',['CreateProceduralPolarGrating.m',['../_create_procedural_polar_grating_8m.html',1,'']]],
  ['createproceduralpseudoyellowgrating_2em_13',['CreateProceduralPseudoYellowGrating.m',['../_create_procedural_pseudo_yellow_grating_8m.html',1,'']]],
  ['createproceduralsinesmoothedgrating_2em_14',['CreateProceduralSineSmoothedGrating.m',['../_create_procedural_sine_smoothed_grating_8m.html',1,'']]],
  ['createproceduralsinesquaregrating_2em_15',['CreateProceduralSineSquareGrating.m',['../_create_procedural_sine_square_grating_8m.html',1,'']]],
  ['createproceduralsmoothdisc_2em_16',['CreateProceduralSmoothDisc.m',['../_create_procedural_smooth_disc_8m.html',1,'']]]
];
